# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-deps:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-deps:
        patterns:
          - '*'

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-deps:
        patterns:
          - '*'
