#!/bin/bash
set -eux

env | sort
pwd

# jupyter-offlinenotebook is automatically installed by repo2docker.
# Uninstall to avoid conflicts
jupyter labextension uninstall --no-build jupyter-offlinenotebook

# Upgrade jupyterlab if necessary
conda install jupyterlab=2

# repo2docker copies this repo into $HOME which means jupyter labextension
# picks up hidden dot files and runs into problems so install from a
# different directory
SRCDIR=/srv/conda/src/jupyter-offlinenotebook
mkdir -p "$SRCDIR"
cp -a * "$SRCDIR"
cd "$SRCDIR"
python -m pip install .
jupyter labextension link --debug
